import type { Metadata } from "next";
import "./globals.css";
import "98.css";
import { ProcessBar } from "@/components/process-bar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="antialiased">
      <body>
        {children}
        <ProcessBar />
      </body>
    </html>
  );
}
